name: Angular
on:
  push:
    branches: [ main ]
    paths:
      - Laudari.Webapp/laudari-webapp/**
      - .github/workflows/angular.yml

  pull_request:
    branches: [ main ]
    paths:
      - Laudari.Webapp/laudari-webapp/**
      - .github/workflows/angular.yml

defaults:
  run:
    working-directory: Laudari.Webapp/laudari-webapp

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - name: npm ci and npm run build
        run: |
          npm ci
          npm run build
