name: Build Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


defaults:
  run:
    working-directory: Laudari.WebApp/laudari-webapp


jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2         
          
      - name: Angular Deploy gh-pages Actions
        # You may pin to the exact commit or the version.
        # uses: AhsanAyaz/angular-deploy-gh-pages-actions@0e4f1a953d00116ca38fbf1bcdb37f91923015ef
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: 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
          build_configuration: production
          base_href: /usabdome
          run_lint: false
