name: .NET

on:
  push:
    branches: [ main ]
    paths:
      - Laudari.Backend/**
      - .github/workflows/dotnet.yml

  pull_request:
    branches: [ main ]
    paths:
      - Laudari.Backend/**
      - .github/workflows/dotnet.yml


defaults:
  run:
    working-directory: Laudari.Backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
